"""Static model catalog data."""
from __future__ import annotations

from unified_llm.catalog.types import ModelInfo

MODELS: tuple[ModelInfo, ...] = (
    # --- Anthropic ---
    ModelInfo(
        id="claude-opus-4-6",
        provider="anthropic",
        display_name="Claude Opus 4.6",
        context_window=200_000,
        max_output=32_000,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=15.0,
        output_cost_per_million=75.0,
        aliases=("claude-opus", "opus"),
    ),
    ModelInfo(
        id="claude-sonnet-4-5-20250929",
        provider="anthropic",
        display_name="Claude Sonnet 4.5",
        context_window=200_000,
        max_output=16_000,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=3.0,
        output_cost_per_million=15.0,
        aliases=("claude-sonnet", "sonnet"),
    ),
    ModelInfo(
        id="claude-haiku-4-5-20251001",
        provider="anthropic",
        display_name="Claude Haiku 4.5",
        context_window=200_000,
        max_output=8_192,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=False,
        input_cost_per_million=0.80,
        output_cost_per_million=4.0,
        aliases=("claude-haiku", "haiku"),
    ),
    # --- OpenAI ---
    ModelInfo(
        id="gpt-4o",
        provider="openai",
        display_name="GPT-4o",
        context_window=128_000,
        max_output=16_384,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=False,
        input_cost_per_million=2.50,
        output_cost_per_million=10.0,
        aliases=("4o",),
    ),
    ModelInfo(
        id="gpt-4o-mini",
        provider="openai",
        display_name="GPT-4o Mini",
        context_window=128_000,
        max_output=16_384,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=False,
        input_cost_per_million=0.15,
        output_cost_per_million=0.60,
        aliases=("4o-mini",),
    ),
    ModelInfo(
        id="o3",
        provider="openai",
        display_name="O3",
        context_window=200_000,
        max_output=100_000,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=10.0,
        output_cost_per_million=40.0,
        aliases=(),
    ),
    ModelInfo(
        id="o3-mini",
        provider="openai",
        display_name="O3 Mini",
        context_window=200_000,
        max_output=100_000,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=1.10,
        output_cost_per_million=4.40,
        aliases=(),
    ),
    ModelInfo(
        id="o4-mini",
        provider="openai",
        display_name="O4 Mini",
        context_window=200_000,
        max_output=100_000,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=1.10,
        output_cost_per_million=4.40,
        aliases=(),
    ),
    # --- Gemini ---
    ModelInfo(
        id="gemini-2.5-pro",
        provider="gemini",
        display_name="Gemini 2.5 Pro",
        context_window=1_000_000,
        max_output=65_536,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=1.25,
        output_cost_per_million=10.0,
        aliases=("gemini-pro",),
    ),
    ModelInfo(
        id="gemini-2.5-flash",
        provider="gemini",
        display_name="Gemini 2.5 Flash",
        context_window=1_000_000,
        max_output=65_536,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=True,
        input_cost_per_million=0.15,
        output_cost_per_million=0.60,
        aliases=("gemini-flash",),
    ),
    ModelInfo(
        id="gemini-2.0-flash",
        provider="gemini",
        display_name="Gemini 2.0 Flash",
        context_window=1_000_000,
        max_output=8_192,
        supports_tools=True,
        supports_vision=True,
        supports_reasoning=False,
        input_cost_per_million=0.10,
        output_cost_per_million=0.40,
        aliases=(),
    ),
)
